### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by noprocede** [msshnt/move-pane#1]
**HI! BEFORE OF ALL THANK YOU FOUR YOUR TIME! THE PACKCAGE IS PERFECT!**

I founded a error when I tried to move a pane to a direction where is not another pane. For example, if you have two panes in a single row and try to move one of them to above/below, appears the following error:

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Unknown Windows Version
**Thrown From**: 'move-panes' package, vundefined

### Stack Trace

**Uncaught TypeError: Cannot read property '0' of undefined**

```
At C:\Users\jorge\.atom\packages\move-panes\lib\move-panes.coffee:31

TypeError: Cannot read property '0' of undefined
    at Object.move (file:///C:/Users/jorge/.atom/packages/move-panes/lib/move-panes.coffee:31:6)
    at Object.moveRight (file:///C:/Users/jorge/.atom/packages/move-panes/lib/move-panes.coffee:11:18)
    at atom-workspace.atom.commands.add.move-panes:move-right (file:///C:/Users/jorge/.atom/packages/move-panes/lib/move-panes.coffee:4:70)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jorge\AppData\Local\atom\app-1.12.6\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\jorge\AppData\Local\atom\app-1.12.6\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\jorge\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\jorge\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\jorge\AppData\Local\atom\app-1.12.6\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\jorge\AppData\Local\atom\app-1.12.6\resources\app.asar\src\window-event-handler.js:3:59)
```

### Commands

```
     -1:12.9.0 window:focus-pane-above (atom-text-editor.editor.is-focused)
     -1:11.2.0 move-panes:move-down (atom-text-editor.editor.is-focused)
     -1:09.8.0 move-panes:move-up (atom-text-editor.editor.is-focused)
  2x -1:09.1.0 move-panes:move-right (atom-text-editor.editor.is-focused)
     -0:57.4.0 move-panes:move-left (atom-text-editor.editor.is-focused)
     -0:43.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:25 maximize-panes:maximize (atom-text-editor.editor.is-focused)
     -0:22.4.0 editor:add-selection-below (atom-text-editor.editor.is-focused)
  2x -0:21.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:21 core:cancel (atom-text-editor.editor.is-focused)
     -0:20.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:20.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:20 move-panes:move-down (atom-text-editor.editor.is-focused)
     -0:19 move-panes:move-up (atom-text-editor.editor.is-focused)
     -0:18.1.0 move-panes:move-left (atom-text-editor.editor.is-focused)
     -0:16.5.0 move-panes:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "pigments",
      "alignment",
      "php-cs-fixer",
      "open-on-github"
    ],
    "excludeVcsIgnoredPaths": false,
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "close-tags",
      "emmet"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
alignment, v1.1.5 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-ui, v1.3.8 (active)
auto-encoding, v0.6.2 (active)
close-tags, v0.6.0 (inactive)
color-picker, v2.2.3 (active)
emmet, v2.4.3 (active)
file-types, v0.5.4-p1 (active)
highlight-selected, v0.11.2 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
maximize-panes, v0.2.0 (active)
minimap, v4.25.7 (active)
monokai, v0.18.0 (inactive)
move-pane, v0.1.0 (active)
php-cs-fixer, v4.0.0 (inactive)
pigments, v0.37.0 (inactive)
split-diff, v1.1.0 (inactive)
two-light-ui, v1.1.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

Again. Thank you very much.

**Comment by msshnt** [comment]
> Thrown From: 'move-panes' package, vundefined

It seems that you were navigated to a wrong repo.
I'm considering renaming the package to avoid confusion.
